name: Release

on:
  release:
    types: [published]

jobs:
  artifact:
    uses: yonatankarp/github-actions/.github/workflows/release.yml@v1
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets:
      GITHUB_PAT: ${{ secrets.REVIEWER_GITHUB_TOKEN }}
