name: Release

on:
  release:
    types: [published]

jobs:
  artifact:
    uses: yonatankarp/github-actions/.github/workflows/release.yml@fix_release_pipeline
    with:
      tag: ${GITHUB_REF#refs/*/}
    secrets:
      GITHUB_PATH: ${{ secrets.REVIEWER_GITHUB_TOKEN }}
